version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: booksy-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booksy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - booksy-network 

  minio:
    image: minio/minio
    container_name: booksy-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - booksy-network

networks:
  booksy-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
